[package]
name = "pallocator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pgx = { version = "=0.5.0-beta.0", features = ["pg14"] }
